# Generated by Django 4.0.6 on 2022-10-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislikelike',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dislikelike',
            new_name='dislike',
        ),
    ]
