# Generated by Django 4.0.6 on 2022-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggings', '0002_rename_dislikelike_comment_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
